name: .conda
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.3.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_3
  - attrs=25.3.0=pyh71513ae_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - brotli-python=1.1.0=py39ha51f57c_3
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39ha55e580_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.9.23=py39hd8ed1ab_0
  - cython=3.1.3=py39hc6ecc89_2
  - debugpy=1.8.16=py39h1f3cc84_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - flatbuffers=24.3.25=h63175ca_0
  - frozendict=2.4.6=py39ha55e580_0
  - gast=0.6.0=pyhd8ed1ab_0
  - giflib=5.2.2=h64bf75a_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - greenlet=3.2.4=py39hdb6649d_0
  - grpcio=1.71.0=py39h5aa6a49_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py39ha907541_100
  - hdf5=1.14.6=nompi_he30205f_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h63175ca_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.18.1=pyh7428d3b_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.1=pyhd8ed1ab_0
  - jpeg=9e=hcfcfb64_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - keras=3.10.0=pyh753f3f9_0
  - krb5=1.21.3=hdf4eb48_0
  - libabseil=20250127.0=cxx17_h4eb7d71_0
  - libaec=1.1.4=h20038f6_0
  - libblas=3.11.0=1_hf2e6a31_mkl
  - libcblas=3.11.0=1_h2a3cdd5_mkl
  - libcurl=8.17.0=h43ecb02_0
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=h35301be_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=1_hf9ab0e9_mkl
  - libpng=1.6.51=h7351971_0
  - libprotobuf=5.29.3=he9d8c4a_0
  - libre2-11=2024.07.02=hd248061_3
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.6=h4fa8253_0
  - lxml=6.0.0=py39hfee6a47_0
  - markdown=3.8.2=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2025.3.0=hac47afa_454
  - ml_dtypes=0.5.1=py39h2366fc2_0
  - multitasking=0.0.12=pyhd8ed1ab_0
  - namex=0.1.0=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.0.2=py39h60232e0_1
  - openssl=3.6.0=h725018a_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.17.0=py39h9da4e41_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h743b7ac_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - peewee=3.18.2=py39h6ae13e9_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - platformdirs=4.3.8=pyhe01879c_0
  - pmdarima=2.0.4=py39ha55e580_2
  - prompt-toolkit=3.0.51=pyha770c72_0
  - protobuf=5.29.3=py39ha51f57c_0
  - psutil=7.0.0=py39ha55e580_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.9.25=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-flatbuffers=24.3.25=pyhe33e51e_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py39h5fb4b08_0
  - pyzmq=27.0.2=py39h248659b_0
  - re2=2024.07.02=haf4117d_3
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.1.0=pyhe01879c_0
  - rpds-py=0.27.0=py39hcab59ba_0
  - scikit-learn=1.6.1=py39hdd013cc_0
  - scipy=1.13.1=py39h1a10956_0
  - setuptools=80.9.0=py39haa95532_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlalchemy=2.0.43=py39h0802e32_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py39h9e4d2f2_0
  - tbb=2022.3.0=hd094cb3_1
  - tensorboard=2.19.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py39hcbf5309_2
  - tensorflow=2.19.1=cpu_py39h6605a60_0
  - tensorflow-base=2.19.1=cpu_py39h4cf5749_0
  - termcolor=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py39h0802e32_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py39haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.3=py39h0802e32_0
  - xz=5.6.4=h4754444_1
  - yfinance=0.2.57=pyhd8ed1ab_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.23.0=py39h0802e32_3
  - pip:
      - filelock==3.19.1
      - finnhub-python==2.4.25
      - fsspec==2025.10.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - sympy==1.14.0
      - torch==2.8.0
prefix: C:\Users\amjit\miniconda3\envs\.conda
